/* ================================================================ the Loanable Funds problem set (graded Oct 3: 22 of 25)
   His real questions, reworded only where a fill-in had to become multiple choice.
     m:2  the two he lost points on (Questions 9 and 11)
     m:1  the ones he got right — problem-set style                                    */
QB = QB.concat([
 {tp:"lf",ps:5,sec:"g-lf-model",m:1,t:"mc",q:"According to the loanable funds model, there is:",a:"one financial market in which all savers and borrowers interact",w:["a separate financial market for every type of borrower","a nominal interest rate that adjusts to equate saving and borrowing","no relationship at all between saving and investment"],e:"One market for everyone — and it is the real rate, not the nominal one, that adjusts."},
 {tp:"lf",ps:5,sec:"g-lf-model",m:1,t:"mc",q:"If there is a surplus of loanable funds, then:",a:"neither curve shifts; quantity supplied falls and quantity demanded rises as the rate falls to equilibrium",w:["neither curve shifts; quantity supplied rises and quantity demanded falls as the rate rises to equilibrium","the supply of loanable funds shifts left and the demand shifts right until they meet","the supply of loanable funds shifts right and the demand shifts left until they meet"],e:"A surplus means the rate is too high. It falls, and you move along both curves; nothing shifts."},
 {tp:"lf",ps:5,sec:"g-lf-model",m:1,t:"mc",q:"“If the real interest rate declines, investment increases.” This statement is:",a:"true if the rate fell because supply increased",w:["true if the rate fell because demand decreased","true in all circumstances","false in all circumstances"],e:"More saving lowers the rate and raises the quantity invested. If demand fell instead, the rate falls and investment falls with it."},
 {tp:"lf",ps:5,sec:"g-lf-model",m:1,t:"mc",q:"According to the Solow model, why does the loanable funds market matter for long-run growth?",a:"Saving and investment finance the physical capital used in production",w:["The real interest rate permanently sets the unemployment rate","Household borrowing is the main source of technological progress","The loanable funds market sets the long-run inflation rate"],e:"Saving becomes investment, and investment builds the capital stock in the Solow model."},
 {tp:"lf",ps:5,sec:"g-lf-rates",m:1,t:"mc",q:"Which statement correctly distinguishes the nominal and real interest rates?",a:"The nominal rate is how fast a deposit’s dollar value grows; the real rate is how fast its purchasing power grows",w:["The nominal rate adjusts for inflation, while the real interest rate does not adjust for it","Both the nominal and the real interest rates measure changes in the purchasing power of money","The real rate measures price changes, while the nominal rate measures inflation expectations"],e:"Dollars versus purchasing power. The real rate is the one adjusted for inflation."},
 {tp:"lf",ps:5,sec:"g-lf-rates",m:1,ap:true,t:"mc",q:"The real interest rate is 4 percent and there is deflation of 1 percent. The nominal interest rate is:",a:"3 percent",w:["5 percent","6 percent","2 percent"],e:"Nominal = real + inflation = 4 + (−1) = 3. Deflation is negative inflation, so you subtract."},
 {tp:"lf",ps:5,sec:"g-lf-rates",m:1,t:"mc",q:"Which statement about ex-ante and ex-post real interest rates is true?",a:"The ex-post real rate reflects actual changes in purchasing power",w:["The ex-ante real rate can only be known after inflation occurs","The ex-ante and ex-post real rates are always identical in the long run","The ex-post real rate is based on inflation expectations set by the government"],e:"Ex-ante uses expected inflation, before the fact; ex-post uses the inflation that actually happened."},
 {tp:"lf",ps:5,sec:"g-lf-crowd",m:1,t:"mc",q:"Crowding out occurs when private investment spending declines because:",a:"a budget deficit makes interest rates rise",w:["a budget deficit makes interest rates fall","a budget surplus makes interest rates rise","a budget surplus makes interest rates fall"],e:"The government borrows, the real rate rises, and private borrowers are priced out."},

 {tp:"lf",ps:5,sec:"g-lf-shifts",m:1,ap:true,t:"mc",q:"The number of retirees is growing more slowly than the number of people joining the workforce. In the loanable funds market:",a:"supply shifts right; the real rate falls and the quantity rises",w:["supply shifts left; the real rate rises and the quantity falls","demand shifts right; the real rate rises and the quantity rises","demand shifts left; the real rate falls and the quantity falls"],e:"Workers save and retirees draw savings down, so more workers means more saving: one shift, of supply, down and to the right."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:2,ap:true,t:"mc",q:"Households become more optimistic and spend more, and businesses become more optimistic about future profits. In the loanable funds market:",a:"the real rate rises; the quantity is ambiguous",w:["the real rate is ambiguous; the quantity rises","the real rate and the quantity are both ambiguous","the real rate falls; the quantity is ambiguous"],e:"You missed this on Problem Set 5 (Question 9). Households spend more, so they save less: supply shifts left. Businesses borrow more: demand shifts right. Both shifts push the rate up; they pull the quantity in opposite directions."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:2,t:"tf",q:"When both loanable funds curves shift, the real interest rate and the quantity of loanable funds can both be ambiguous.",a:false,e:"You missed this on Problem Set 5 (Question 9). False — Canvas’s own comment: “Both variables cannot be ambiguous.” Two shifts always agree on one of the two and disagree on the other, so exactly one is ambiguous."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:2,ap:true,t:"mc",q:"A technology shock raises production costs and makes new investment projects less profitable for firms. The demand for loanable funds:",a:"shifts down and to the left",w:["shifts up and to the right","does not shift; only the supply curve moves","does not shift; firms move along the curve"],e:"You missed this on Problem Set 5 (Question 11). Less profitable projects mean firms want to borrow less at every rate. “Less profitable” is the clue for a leftward shift of demand."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:2,ap:true,t:"mc",q:"Households become less patient and more present-oriented. At the same time, new investment projects become less profitable for firms. In the loanable funds market:",a:"the quantity falls; the real rate is ambiguous",w:["the quantity is ambiguous; the real rate rises","the quantity and the real rate are both ambiguous","the quantity rises; the real rate is ambiguous"],e:"You missed this on Problem Set 5 (Question 11). Less patient households save less: supply shifts left. Less profitable projects: demand shifts left. Both shifts cut the quantity; they push the rate in opposite directions."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:1,t:"mc",q:"Supply shifts left and demand shifts right. Which result is certain?",a:"The real interest rate rises",w:["The real interest rate falls","The quantity of loanable funds rises","The quantity of loanable funds falls"],e:"Both shifts raise the rate. The quantity depends on which curve moves further."},
 {tp:"lf",ps:5,sec:"g-lf-shifts",m:1,t:"mc",q:"Supply and demand for loanable funds both shift left. Which result is certain?",a:"The quantity of loanable funds falls",w:["The quantity of loanable funds rises","The real interest rate rises","The real interest rate falls"],e:"Both shifts cut the quantity. The rate depends on which curve moves further."},

 {tp:"growth",sec:"g-gro-shifts",m:1,ap:true,t:"mc",q:"Households become less patient and save less, and a technology shock raises production costs. In the Solow model the production function and the investment curve both shift down. Steady-state capital, investment and output:",a:"all decrease",w:["all increase","capital falls, but output rises","do not change; only the rate moves"],e:"A lower production function and a lower investment curve meet depreciation at a lower capital stock, so investment and output are lower too."}
]);

/* ================================================================ Problem Set 6 · liquidity preference (due Oct 8)
   Written in the format the real Problem Set 5 used: a scenario, then what each curve does,
   the rate and the quantity. The lesson from his two misses carries over, with one twist:
   money supply is VERTICAL, so the quantity of money follows the supply curve alone and is
   never ambiguous. Only the nominal rate can be.                                             */
QB = QB.concat([
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Model: liquidity preference. Incomes rise across the economy, and at the same time the Federal Reserve increases the money supply. What happens?",a:"The quantity of money rises; the nominal rate is ambiguous",w:["The nominal rate rises; the quantity of money is ambiguous","The nominal rate and the quantity of money are both ambiguous","The quantity of money rises; the nominal rate rises"],e:"Money demand shifts right (rate up); money supply shifts right (rate down, quantity up). The rate is pulled both ways. The quantity follows the vertical supply curve, so it rises."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Model: liquidity preference. Incomes rise across the economy, and at the same time the Federal Reserve decreases the money supply. What happens?",a:"The nominal rate rises; the quantity of money falls",w:["The nominal rate rises; the quantity of money is ambiguous","The nominal rate is ambiguous; the quantity of money falls","The nominal rate falls; the quantity of money rises"],e:"Money demand right and money supply left both push the rate up. The quantity follows supply, so it falls. Nothing is ambiguous here."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Model: liquidity preference. A recession lowers incomes, and the Federal Reserve responds by increasing the money supply. What happens?",a:"The nominal rate falls; the quantity of money rises",w:["The nominal rate is ambiguous; the quantity of money rises","The nominal rate falls; the quantity of money is ambiguous","The nominal rate rises; the quantity of money falls"],e:"Money demand left and money supply right both push the rate down. The quantity follows supply, so it rises."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Model: liquidity preference. The aggregate price level falls, and at the same time the Federal Reserve decreases the money supply. What happens?",a:"The quantity of money falls; the nominal rate is ambiguous",w:["The nominal rate falls; the quantity of money is ambiguous","The quantity of money falls; the nominal rate falls","The nominal rate and the quantity of money are both ambiguous"],e:"Money demand left (rate down); money supply left (rate up, quantity down). The rate is pulled both ways; the quantity follows supply and falls."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,t:"tf",q:"In the liquidity preference model, when both curves shift, the quantity of money can be ambiguous.",a:false,e:"False. Money supply is vertical, so the quantity of money is wherever the Fed puts the supply curve. Only the nominal rate can be ambiguous."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Model: liquidity preference. Households grow wary of stocks and prefer to keep more money on hand. Nothing else changes. What happens?",a:"Demand shifts right; supply does not shift; the rate rises; the quantity is unchanged",w:["Demand shifts right; supply does not shift; the rate rises; the quantity rises","Demand does not shift; supply shifts left; the rate rises; the quantity falls","Demand shifts left; supply does not shift; the rate falls; the quantity is unchanged"],e:"A change in preferences shifts money demand right. With a vertical supply curve, only the rate moves."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,t:"mc",q:"The nominal interest rate falls and nothing else changes. What happens to money demand?",a:"No shift: the quantity of money demanded rises along the curve",w:["It shifts right, because money is cheaper to hold","It shifts left, because bonds now pay less","No shift: the quantity of money demanded falls along the curve"],e:"A change in the rate itself is a move along the curve. Only income, the price level, preferences or policy shift it."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,t:"mc",q:"Which pair correctly matches each model with the rate it sets?",a:"Loanable funds: real, long run. Liquidity preference: nominal, short run",w:["Loanable funds: nominal, long run. Liquidity preference: real, short run","Loanable funds: real, short run. Liquidity preference: nominal, long run","Loanable funds: nominal, short run. Liquidity preference: real, long run"],e:"His warning: the biggest mistake is combining or confusing the two models."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"Households become less patient and save less. Which model shows this, and what shifts?",a:"Loanable funds: supply shifts left",w:["Liquidity preference: money demand shifts left","Liquidity preference: money supply shifts left","Loanable funds: demand shifts right"],e:"Saving is the supply of loanable funds. The liquidity preference model is about holding money, not about saving."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,ap:true,t:"mc",q:"The Federal Reserve increases the money supply. Which model shows this first, and what happens?",a:"Liquidity preference: supply shifts right and the nominal rate falls",w:["Loanable funds: supply shifts right and the real rate falls","Liquidity preference: demand shifts right and the nominal rate rises","Loanable funds: demand shifts left and the real rate falls"],e:"The Fed controls the vertical money supply curve. In the short run the nominal rate falls: the liquidity effect."},
 {tp:"money",ps:6,sec:"g-mon-lp",m:1,t:"mc",q:"Money demand shifts right and money supply shifts right. Which result is certain?",a:"The quantity of money rises",w:["The quantity of money falls","The nominal interest rate rises","The nominal interest rate falls"],e:"The quantity follows supply. The rate depends on which curve moves further."}
]);
